name: Node CI
on:
  pull-request:
    branches: [master,NasirAbdullahSyed-patch-1]
jobs:
  test_pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - name: Testing
        - run: npm test
      - name: Running
        - run: npm run build
