name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checking repository...
      uses: actions/checkout@v2
    - name: NPM clean installing...
      run: npm ci
    - name: Building...
      run: npm run build --if-present
    - name: Testing...
      run: npm test -- --coverage
    - name: Uploading tests coverage...
      run: codecov/codecov-action@v1
      
      #jezeli repo prywatne
    - name: Uploading coverage to Codecov...
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
