name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gerrit450/225-github-actions-demo #runs action of deployment. first string can be anything etc, string/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.GITACTIONS}}
          heroku_app_name: "applicationstage"